Loam/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.Composing;
using Umbraco.Web.Models;

namespace Loam.ViewModels
{
    public  class  CategoryViewModel : ContentModel
    {
   
        public CategoryViewModel() : base(Current.UmbracoContext.PublishedRequest.PublishedContent)
        //public CategoryViewModel()
        {
            Categories = new List<CategoryViewModel>();
           Products = new List<ProductViewModel>();
        }

        public CategoryViewModel(IPublishedContent content) : base(content)
        {
            Categories = new List<CategoryViewModel>();
            Products = new List<ProductViewModel>();
        }

        public IList<ProductViewModel> Products { get; set; }

        public string Url { get; set; }

        public string ImageId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public IList<CategoryViewModel> Categories { get; set; }

      

        public string BannerImageUrl { get; set; }

        public Guid CategoryId { get; set; }

        public Guid CatalogId { get; set; }

        public int TotalProducts { get; set; }
        public int PageNumber { get; set; }
        public int PageSize { get; set; }






    }
}

Loam/ViewModels/ProductViewModel.cs
using System;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.Composing;
using Umbraco.Web.Models;

namespace Loam.ViewModels
{
    public class ProductViewModel : ContentModel
    {
        public ProductViewModel(IPublishedContent content) : base(content)
        {

        }

        public ProductViewModel() : base(Current.UmbracoContext.PublishedRequest.PublishedContent)
       
        {
            Products = new List<ProductViewModel>();
            Variants = new List<ProductViewModel>();
            Properties = new List<ProductPropertiesViewModel>();
        }

        public bool IsVariant { get; set; }

        public bool IsProductFamily { get; set; }
        public IList<ProductViewModel> Products { get; set; }

        public string Tax { get; set; }
        public bool IsOrderingAllowed { get; set; }
     
        public string ThumbnailImageUrl { get; set; }
        public string VariantSku { get; set; }
        public string Sku { get; set; }
        public string PrimaryImageMediaId { get; set; }
       
        public IList<ProductViewModel> Variants { get; set; }

        public IList<ProductPropertiesViewModel> Properties { get; set; }


     

        public string LongDescription { get; set; }
        public string ShortDescription { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
   

        public string Price { get; set; }
        public double? Rating { get; set; }
    }
}

Loam/ViewModels/ProductsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.Composing;
using Umbraco.Web.Models;

namespace Loam.ViewModels
{
    public class ProductsViewModel : ContentModel
    {
        //public ProductsViewModel(IPublishedContent content) : base(content)
        //{

        //}

        public ProductsViewModel() : base(Current.UmbracoContext.PublishedRequest.PublishedContent)

        {
            Products = new List<ProductViewModel>();
        }

        public IList<ProductViewModel> Products;
    }
}

Loam/Controllers/CatalogController.cs
using Loam.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ucommerce.Api;
using Ucommerce.Catalog;
using Ucommerce.EntitiesV2;
using Ucommerce.Infrastructure;
using Ucommerce.Infrastructure.Logging;
using Umbraco.Web.Models;

namespace Loam.Controllers
{
    public class CatalogController : Umbraco.Web.Mvc.RenderMvcController
    {

        public override ActionResult Index(ContentModel model)
        {
           
            string category = Request.QueryString["category"];


            var query = from prod in Product.All() select prod;

            List<ProductViewModel> list = new List<ProductViewModel>();

            foreach (var product in query)
            {
                foreach (var categories in product.CategoryProductRelations.Where(x => x.Category.Name == category))
                {
                    foreach (var products in categories.Product.ProductDescriptions)
                    {
                        IUrlService urlService = ObjectFactory.Instance.Resolve<IUrlService>();

                        ProductCatalog catalog = ProductCatalog.SingleOrDefault(x => x.Name == "Loam");

                        Category category1 = Category.SingleOrDefault(x => x.Name == category);
                   
                        Product product1 = Product.SingleOrDefault(x => x.Name == products.DisplayName);
                    
                        string productUrl = urlService.GetUrl(catalog, category1, product1);
                
                       var productImage = Umbraco.Media(product.PrimaryImageMediaId);

                        if (productImage != null)
                        {
                            list.Add(new ProductViewModel { Name = product.Name, ThumbnailImageUrl = productImage.Url, ShortDescription = products.ShortDescription, Url = productUrl });
                        }


                    }
                   
                }
            
                
            }

      

            return PartialView("ProductsView", list);

       

        }

      


    }
}

Loam/Controllers/CategoryController.cs
using Loam.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;
using Ucommerce.Api;
using Ucommerce.Catalog;
using Ucommerce.EntitiesV2;
using Ucommerce.Infrastructure;


using Umbraco.Web.Mvc;


namespace Loam.Controllers
{
    public class CategoryController : SurfaceController
    {
        public ICatalogLibrary CatalogLibrary => ObjectFactory.Instance.Resolve<ICatalogLibrary>();
     

 
        public ActionResult Index()
        {

                var rootCategories = CatalogLibrary.GetRootCategories();
            
                List<CategoryViewModel> list = new List<CategoryViewModel>();

            


            foreach (var categories in rootCategories)
                {
  
                IUrlService urlService = ObjectFactory.Instance.Resolve<IUrlService>();

                ProductCatalog catalog = ProductCatalog.SingleOrDefault(x => x.Name == "Loam");
          

                Category category1 = Category.FirstOrDefault(x => x.Name == categories.Name);

                string productUrl = urlService.GetUrl(catalog, category1);

                list.Add(new CategoryViewModel { Name = categories.Name, Url = productUrl });
            
                };

                return PartialView("CategoryNavigation", list as IEnumerable<CategoryViewModel>);
    
        }

     
    }
}

Loam/Controllers/DesignerController.cs
using Loam.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ucommerce.Api;
using Ucommerce.Catalog;
using Ucommerce.EntitiesV2;
using Ucommerce.Infrastructure;
using Ucommerce.Infrastructure.Logging;
using Ucommerce.Search;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace Loam.Controllers
{
    public class DesignerController : RenderMvcController
    {
      
        // GET: Designer
        public ActionResult Index(ContentModel model, string color)
        {
                

            //To do, render a macro in designer thats loads all the products..
            return View("/views/designer.cshtml", model.Content);
        }

        [HttpGet]
        public ActionResult Index()
        {
            string color = Request.QueryString["color"];


            Product product = Product.SingleOrDefault(z => z.Name == color);
            if (product != null)
            {
                //Response.Write(product.Name);
            }



            return View("/views/designer.cshtml");
        }


    }
}

Loam/Controllers/HomeController.cs
using System.Web.Mvc;


using Umbraco.Web.Mvc;

using Umbraco.Web.Models;


namespace Loam.Controllers
{
    
    public class HomeController : RenderMvcController
    {

        public  ActionResult Index(ContentModel model, string category)
        {
            //https://localhost:44354/?category=herre
          
            return View("/views/home.cshtml", model.Content);
        }



 
    }
}

Loam/Controllers/ProductController.cs
using Loam.ViewModels;

using System.Collections.Generic;

using System.Web.Mvc;
using Ucommerce.Api;
using Ucommerce.Catalog;
using Ucommerce.EntitiesV2;
using Ucommerce.Infrastructure;
using Ucommerce.Infrastructure.Logging;

using Umbraco.Web.Models;

namespace Loam.Controllers
{
    public class ProductController : Umbraco.Web.Mvc.RenderMvcController
    {

     
        // GET: ProductPage
        public override ActionResult Index(ContentModel model)
        {
            var transactionLibrary = ObjectFactory.Instance.Resolve<ITransactionLibrary>();

            string getProduct = Request.QueryString["product"];

            //get curret product
            Product product = Product.SingleOrDefault(z => z.Name == getProduct);

            //Init a view model
            var productViewModel = new ProductViewModel(model.Content);


            
            var productImage = Umbraco.Media(product.PrimaryImageMediaId);

            productViewModel.Name = product.Name;

            productViewModel.PrimaryImageMediaId = productImage.Url;

            //the MapVariants is a method for my Ilist variants
            productViewModel.Variants = MapVariants(product.Variants);
            //
            productViewModel.IsVariant = false;
        
          


            //Response.Write(MapProductProperties(product));
            productViewModel.Properties = MapProductProperties(product);

            //foreach (var props in product.Variants)
            //{
            //    foreach (var ProductDefinition in props.ProductProperties)
            //    {
            //        Response.Write(ProductDefinition.Value);
            //    }
            //}



            foreach (var descriptions in product.ProductDescriptions)
            {
                productViewModel.LongDescription = descriptions.LongDescription;
                    
            }

            foreach (var prices in product.ProductPrices)
            {
               
               
                foreach (var price in prices.Product.ProductPrices)
                {
                   
              
                    var formattedPrice = transactionLibrary.FormatCurrency(price.Price.Amount, "da-DK");
                    productViewModel.Price = formattedPrice;

              
                }
            }




            return CurrentTemplate(productViewModel);
        }

        private IList<ProductPropertiesViewModel> MapProductProperties(Product product)
        {
            var productProperties = new List<ProductPropertiesViewModel>();

      
            foreach (var prod in product.Variants)
            {

                foreach (var prop in prod.ProductProperties)
                {
                   
                


                    string[] value = { prop.Value };

                    productProperties.Add(new ProductPropertiesViewModel { PropertyName = prop.ProductDefinitionField.Name, Values = value });

                

                }



            }

           

            return productProperties;
     
        }
 
        private IList<ProductViewModel> MapVariants(IEnumerable<Product> product)
        {
           
            var variantModels = new List<ProductViewModel>();



            foreach (var currentVariant in product)
            {
                var variantImage = Umbraco.Media(currentVariant.PrimaryImageMediaId);



                if (variantImage != null)
                {
             
                
                    var productModel = new ProductViewModel
                    {
                        Name = currentVariant.Name,

                        PrimaryImageMediaId = variantImage.Url,
                        IsVariant = true

                    };

                    variantModels.Add(productModel);
                }

                
            }

         
            return variantModels;
        }


    



    }

}

Loam/Views/About.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage
    @{
        Layout = "Layout.cshtml";
}
<div class="container bg-white">
	<div class="container pt-5 pb-5">

		<h1> @Model.Value("pageTitle")</h1>

		<p>
			@Model.Value("pageContent")
		</p>

	</div>
</div>

Loam/Views/Catalog.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage


<div class="container" style="color:red;">

    @Umbraco.RenderMacro("UcommerceBreadcrumbs")
</div>

Loam/Views/Category.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Category>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}

Loam/Views/Designer.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "Layout.cshtml";
}


<style>



    .btn-circle.btn-sm {
        width: 30px;
        height: 30px;
        padding: 6px 0px;
        border-radius: 15px;
        font-size: 8px;
        text-align: center;
    }

    .btn-circle.btn-md {
        width: 50px;
        height: 50px;
        padding: 7px 10px;
        border-radius: 25px;
        font-size: 10px;
        text-align: center;
    }

    .btn-circle.btn-xl {
        width: 70px;
        height: 70px;
        padding: 10px 16px;
        border-radius: 35px;
        font-size: 12px;
        text-align: center;
    }
</style>

<div class="container">
   
    <div class="row mt-5">
        <div class="col-lg-2 bg-white pt-2 ">
            <div id="1" class="col-md-12 col-xs-12 text-center card pt-5 mt-1 pb-4 " onclick="ShowContent(this.id)">
                <i class="fas fa fa-image fa-2x"></i>
                <p class=" d-none d-sm-block">
                    Upload motiv
                </p>
            </div>
            <div id="2" class="col-md-12 col-xs-12 text-center card pt-5 mt-3  pb-4" onclick="ShowContent(this.id)">
                <i class="fas fa fa-image fa-2x"></i>
                <p class=" d-none d-sm-block">
                    Tilføj font
                </p>
            </div>
            <div id="3" class="col-md-12 col-xs-12 text-center card pt-5 mt-3  pb-4" onclick="ShowContent(this.id)">

                <i class="fas fa fa-image fa-2x"></i>
                <p class=" d-none d-sm-block">
                    Skabeloner
                </p>


                <script>
                    function ShowContent(id) {
                        if (id == 1) {

                            document.getElementById("upload").style.display = '';
                            document.getElementById("images").style.display = 'none';
                            document.getElementById("fonts").style.display = 'none';
                            document.getElementById("content").style.display = '';
                        }
                        if (id == 2) {
                            document.getElementById("fonts").style.display = '';
                            document.getElementById("images").style.display = 'none';
                            document.getElementById("upload").style.display = 'none';
                            document.getElementById("content").style.display = '';
                        }

                        if (id == 3) {

                            document.getElementById("content").style.display = '';
                            document.getElementById("images").style.display = '';
                            document.getElementById("upload").style.display = 'none';
                            document.getElementById("fonts").style.display = 'none';

                        }



                    }
                </script>

            </div>
        </div>

        <div class="col-lg-6  bg-white mx-3  ">
            <div class="col-md-12">
                
    
                @Umbraco.RenderMacro("uCommerceDesignerpageShow")
            </div>
            <div class="col-md-12 pb-5 text-center">
              

                @Umbraco.RenderMacro("uCommerceDesignerpageChoose")


            </div>

        </div>
        <div id="content" style="display:none;" class="col-md-3 pt-3 mt-1  bg-white">
            <div class="col-12" id="upload" style="display:none;">
                <label>
                    Upload et motiv
                </label>


                <form>
                    <div class="form-group">

                        <input type="file" class="form-control-file" id="exampleFormControlFile1">
                    </div>
                </form>


            </div>

            <div class="col-12 mx-1" id="images" style="overflow-y: scroll; height:500px; display:none;">
                @Umbraco.RenderMacro("uCommerceDesignpageMotives")
         



            </div>
            <div class="col-12 pt-1" id="fonts">
                <label>
                    Tilføj tekst
                </label>
                <input type="text" class="form-control">
                <p>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                        <label class="form-check-label" for="exampleRadios1">
                            Ariel
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
                        <label class="form-check-label" for="exampleRadios2">
                            New Times Roman
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
                        <label class="form-check-label" for="exampleRadios2">
                            Lato
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
                        <label class="form-check-label" for="exampleRadios2">
                            Roboto
                        </label>
                    </div>
                </p>
            </div>

        </div>

    </div>



</div>

Loam/Views/Home.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage

@{
    Layout = "Layout.cshtml";
    //   @(Request.ApplicationPath + "Layout.cshtml")
}


@Umbraco.RenderMacro("UcommerceHomeCatalog");

Loam/Views/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="@(Request.ApplicationPath + "Content/bootstrap.min.css")" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />

    <link href="@(Request.ApplicationPath + "Content/sticky-footer-navbar.css")" rel="stylesheet" />

    <link href="@(Request.ApplicationPath + "Content/Custom.css")" rel="stylesheet" />
</head>
<body>


    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="https://localhost:44354/"><img src="@(Request.ApplicationPath + "../Media/logo.png")" /></a>


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    @Html.Action("Index", "Category")

                    @*@Html.Action("Index", "CategoryNavigation")*@



                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Min konto   <i class="fas fa-user"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Kurv   <i class="fas fa-shopping-cart"></i></a>
                    </li>
                </ul>




            </div>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNav">
                <ul class="navbar-nav justify-content-center">
                    <li class="nav-item ">
                        <a class="nav-link" style="color:white" href="#">
                            <i class="fa fa-truck"></i> Fri levering over 300
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color:white" href="#">
                            <i class="fa fa-comments"></i>  Kundeservice mellem 08.00 - 16.00
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color:white" href="#">
                            <i class="fa fa-leaf "></i> Bæredygtige materialer
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>



    <!-- Begin page content -->
    <main role="main" class="pb-5">
        @RenderBody()

    </main>


    <div class="footer">
        <div class="container">

            <div class="float-left">

                <img src=@(Request.ApplicationPath +"Media/cards.png") />
            </div>

            <div class="float-right d-none d-sm-block">
                <a href="/om-os" class="btn btn-link text-white">Om os</a>
                <a href="/retunering" class="btn btn-link text-white">Retunering</a>
                <a href="/handelsbetingelser" class="btn btn-lin text-white">Handelsbetingelser</a>
            </div>




        </div>
    </div>
    <link href="@(Request.ApplicationPath + "Content/Custom.css")" rel="stylesheet" />

    <script src="@(Request.ApplicationPath + "Scripts/jquery-3.0.0.slim.min.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js" integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA==" crossorigin="anonymous"></script>
    <script src="@(Request.ApplicationPath + "Scripts/bootstrap.min.js")"></script>
</body>
</html>

Loam/Views/Product.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage<Loam.ViewModels.ProductViewModel>

@{
    Layout = "Layout.cshtml";
}

@Umbraco.RenderMacro("UcommerceBreadcrumbs")
<div class="container mt-5 bg-white">




    <div class="row">
        <div class="col-md-8">
            <div class="row">

                <div class="col-12 pt-5 ">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Egenskaber</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Produktbeskrivelser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Detaljer</a>
                        </li>
                    </ul>


                    <script>
                        $(function () {
                            $('#myTab li:last-child a').tab('show')
                        })
                    </script>
                </div>

            </div>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                    <div class="row mt-5">
                        <div class="col-4 "><img class="img-thumbnail" src="@(Model.PrimaryImageMediaId)"></div>
                        <div class="col-8 ">
                            <p>     @Model.Name</p>


                            @Html.Raw(@Model.LongDescription);
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">hej</div>
                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">ds</div>
            </div>


        </div>
        <div class="col-md-4 bg-secondary">


            @if (Model.Variants.Count > 0)
            {
                <div class="row">
                    <div class="col-12 pt-5 ">
                        <b>
                            @Model.Name
                        </b>

                    </div>
                    <div class="col-12 pt-2 text-danger ">

                        @Model.Price inkl. moms
                    </div>
                    <div class="col-12 pt-2">

                        <a  href="/designer" class="btn btn-primary btn-block rounded-pill">Design din egen t-shirt</a>
                    </div>

                </div>

                <div class="row">

                    <div class="col-12 pt-2 ">
                        <label class="font-weight-bold">Find et motiv</label>

                    </div>




                    @foreach (var item in Model.Variants.ToList())
                    {
                        <div class="col-3 m-2">
                            <img src="  @item.PrimaryImageMediaId" class="" />


                        </div>
                    }





                </div>
                <div class="row">
                    <div class="col-12 pt-2  text-center">
                        <label>Se alle motiver</label>

                    </div>

                </div>
            }


            <div class="row">

                <div class="col-12 pt-2 ">
                    @if (Model.Properties.Count > 0)
                    {
                        foreach (var group in Model.Properties.GroupBy(item => item.PropertyName))
                        {
                            <label>@group.Key</label>
                            <select class="form-control">
                                @foreach (var value in group)
                                {


                                    foreach (var item in value.Values)
                                    {
                                        <option>
                                            @item
                                        </option>
                                    }



                                }
                            </select>
                        }
                    }



      
                </div>
            </div>

            <div class="row">
                <div class="col-12 pt-5 pb-5">

                    <a href="#" class="btn btn-success btn-block rounded-pill">Bestil</a>
                </div>
            </div>
        </div>
    </div>






</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>

Loam/Views/Return.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "Layout.cshtml";
}
<div class="container-fluid bg-white">
    <div class="container pt-5 pb-5">

        <h1> @Model.Value("pageTitle")</h1>

        <p>
            @Model.Value("pageContent")
        </p>

    </div>
</div>

Loam/Views/Terms.cshtml
@inherits  Umbraco.Web.Mvc.UmbracoViewPage
    @{
        Layout = "Layout.cshtml";
}
<div class="container-fluid bg-white">
    <div class="container pt-5 pb-5">

        <h1> @Model.Value("pageTitle")</h1>

        <p>
            @Model.Value("pageContent")
        </p>

    </div>
</div>